const MED_DATA = [
{"code":"GXA1","cat":"調劑檯","name":"克栓腸溶糖衣錠 Pentoxifylline Tab. (100mg/tab)","loc":"ZCA右2","tag":null},
{"code":"GXA2","cat":"調劑檯","name":"活維D軟膠囊 Calcitriol CAP. (0.5mcg/cap)","loc":"ZAA左","tag":"一般藥品區"},
{"code":"GXA3","cat":"調劑檯","name":"舒脈康膜衣錠【複】Olmesartan/Amlodipine Tab. (40mg/5mg/tab)","loc":"ZDE右1","tag":null},
{"code":"GXA4","cat":"調劑檯","name":"帝拔癲【錠】Valproate TAB. (500mg/tab)","loc":"ZAD約中間","tag":null},
{"code":"GXA5","cat":"調劑檯","name":"特心穩 TELMIsartan (80mg/tab)","loc":"ZCD右","tag":null},
{"code":"GXA6","cat":"調劑檯","name":"倍壓妥【複】Amlodipine/TELMIsartan (5mg/80mg/tab)","loc":"ZCA右","tag":null},
{"code":"GXA7","cat":"調劑檯","name":"得安穩 VALsartan (80mg/tab)","loc":"大庫06","tag":null},
{"code":"GXA8","cat":"調劑檯","name":"蘿菲思 Venlafaxine (75mg/cap)","loc":"ZB身心科右","tag":null},
{"code":"GXB1","cat":"調劑檯","name":"易安穩膜衣錠【複】Exforge (5mg/80mg/tab)","loc":"大庫05","tag":null},
{"code":"GXB2","cat":"調劑檯","name":"貝坦利持續性藥效錠 Mirabegron PR Tab","loc":"ZAB右","tag":"一般藥品區"},
{"code":"GXB3","cat":"調劑檯","name":"吉多利錠 Ketosteril Tab","loc":"ZAB右","tag":"一般藥品區"},
{"code":"GXB4","cat":"調劑檯","name":"驅異樂 Levocetirizine (5mg/tab)","loc":"ZAC中","tag":"一般藥品區"},
{"code":"GXB5","cat":"調劑檯","name":"彌可保 Mecobalamin(Vit.B12) (0.5mg/cap)","loc":"ZAC中","tag":"一般藥品區"},
{"code":"GXB6","cat":"調劑檯","name":"安舒肌 Mephenoxalone (200mg/tab)","loc":"ZAC左1","tag":"一般藥品區"},
{"code":"GXB7","cat":"調劑檯","name":"舒解憂口溶錠 Mirtazapine (30mg/tab)","loc":"ZB身心科中","tag":null},
{"code":"GXB8","cat":"調劑檯","name":"胃莫傷錠 Mosapride citrate (5mg/tab)","loc":"ZB腸胃科右3","tag":null},
{"code":"GXC1","cat":"調劑檯","name":"脂脈優【複】Amlodipine/ATORvastatin Tab. (5mg/20mg/tab)","loc":"ZCB中","tag":null},
{"code":"GXC2","cat":"調劑檯","name":"可道樂膜衣錠【複】VALsartan/Hydrochlorthiazide (80mg/12.5mg/tab)","loc":"ZDA左1","tag":null},
{"code":"GXC3","cat":"調劑檯","name":"利福全【小劑量】Clonazepam Tab. (0.5mg/tab)","loc":"ZDB中","tag":"四級管藥"},
{"code":"GXC4","cat":"調劑檯","name":"克他服寧糖衣錠【小劑量】Diclofenac TAB. (25mg/tab)","loc":"ZBA中","tag":null},
{"code":"GXC5","cat":"調劑檯","name":"萬憂停 Duloxetine HCl (30mg/cap)","loc":"ZB身心科左2","tag":null},
{"code":"GXC6","cat":"調劑檯","name":"可迅持續性藥效錠 Doxazosin Mesylate (4mg/tab)","loc":"大庫03","tag":null},
{"code":"GXC7","cat":"調劑檯","name":"力安穩【(藍)三合一】Exforge HCT (5mg/160mg/12.5mg/tab)","loc":"大庫04","tag":null},
{"code":"GXC8","cat":"調劑檯","name":"耐適恩【錠】Esomeprazole TAB. (40mg/tab)","loc":"大庫區左邊架上","tag":null},
{"code":"GXD1","cat":"調劑檯","name":"捨咳顆粒 Bromhexine HCl Granules (8mg/1g/pkg)","loc":"ZAE約右2","tag":"一般藥品區"},
{"code":"GXD2","cat":"調劑檯","name":"安心平【腸溶膠囊】ASPIRIN E.M. CAP. (100mg/cap)","loc":"ZCA左1","tag":null},
{"code":"GXD3","cat":"調劑檯","name":"富泌舒痰發泡錠 Acetylcysteine TAB. (600mg/tab)","loc":"ZAE右1","tag":"一般藥品區"},
{"code":"GXD4","cat":"調劑檯","name":"合利他命 Thiamine/Vit.B1/Vit.B2","loc":"ZAB中","tag":"一般藥品區"},
{"code":"GXD5","cat":"調劑檯","name":"脈優錠 Amlodipine Tab. (5mg/tab)","loc":"大庫01","tag":null},
{"code":"GXD6","cat":"調劑檯","name":"贊安諾 Alprazolam Tab. (0.5mg/tab)","loc":"ZDB左1","tag":"四級管藥"},
{"code":"GXD7","cat":"調劑檯","name":"立普妥 ATORvastatin (40mg/tab)","loc":"直上","tag":null},
{"code":"GXD8","cat":"調劑檯","name":"康肯 Bisoprolol Tab. (1.25mg/tab)","loc":"直上","tag":null},
{"code":"GXE1","cat":"調劑檯","name":"愛妥糖錠 Pioglitazone (15mg/tab)","loc":"直上","tag":null},
{"code":"GXE2","cat":"調劑檯","name":"恩排糖膜衣錠【大劑量】Empagliflozin Tab. (25mg/tab)","loc":"ZCC左2","tag":null},
{"code":"GXE3","cat":"調劑檯","name":"愛妥蜜【複】Pioglitazone/Metformin (15mg/850mg/tab)","loc":"ZCE左2","tag":null},
{"code":"GXE4","cat":"調劑檯","name":"釋多糖持續性藥效膜衣錠【複】Dapagliflozin/Metformin (10/1000mg/tab)","loc":"ZCE中","tag":null},
{"code":"GXE5","cat":"調劑檯","name":"福適佳膜衣錠 Dapagliflozin Tab. (10mg/tab)","loc":"ZCC左1","tag":null},
{"code":"GXE6","cat":"調劑檯","name":"恩美糖膜衣錠【複】Empagliflozin/Metformin Tab. (12.5mg/850mg/tab)","loc":"ZCC左3偏中","tag":null},
{"code":"GXF1","cat":"調劑檯","name":"高糖優適 VILDAgliptin (50mg/tab)","loc":"直上","tag":null},
{"code":"GXF2","cat":"調劑檯","name":"糖順平膜衣錠【複】Empagliflozin/LINAgliptin Tab. (25mg/5mg/tab)","loc":"ZCC中","tag":null},
{"code":"GXF3","cat":"調劑檯","name":"糖漸平膜衣錠 LINAgliptin (5mg/tab)","loc":"直上","tag":null},
{"code":"GXF4","cat":"調劑檯","name":"醣立定錠 Repaglinide Tab. (1mg/tab)","loc":"ZCE右1","tag":null},
{"code":"GXF5","cat":"調劑檯","name":"普栓達 Dabigatran (110mg/cap)","loc":"ZDD左4","tag":"高警訊"},
{"code":"GXF6","cat":"調劑檯","name":"卡莫德 Tramadol CAP. (50mg/cap)","loc":"ZDE左1","tag":null},
{"code":"GXG1","cat":"調劑檯","name":"利控糖膜衣錠【複】GliMEPIRIDE/Metformin (2/500mg/tab)","loc":"ZDE右2","tag":null},
{"code":"GXG2","cat":"調劑檯","name":"瑪爾胰 GliMEPIRIDE (2mg/tab)","loc":"直上","tag":null},
{"code":"GXG3","cat":"調劑檯","name":"喘克緩釋微粒膠囊(Thoin) Theophylline CAP. (125mg/cap)","loc":"ZDD右1","tag":"高警訊"},
{"code":"GXG4","cat":"調劑檯","name":"妥美亭膜衣錠 Tramadol/Acetaminophen (37.5mg/325mg/tab)","loc":"ZDE左2","tag":null},
{"code":"GY1","cat":"調劑檯","name":"降醣佳 Acarbose Tab. (50mg/tab)","loc":"ZCE左1","tag":null},
{"code":"GY2","cat":"調劑檯","name":"美克糖錠 Metformin (500mg/tab)","loc":"ZCE右2","tag":null},
{"code":"GY3","cat":"調劑檯","name":"汝佳脈膜衣錠 NicaMETATE Citrate (50mg/tab)","loc":"ZCA中","tag":null},
{"code":"GY4","cat":"調劑檯","name":"宜胃 Iwell","loc":"ZB腸胃科左2","tag":null},
{"code":"GY5","cat":"調劑檯","name":"息痛佳音錠 Oxethazaine/Polymigel Tab. (5mg/244mg)","loc":"ZB腸胃科右2","tag":null},
{"code":"共用區1","cat":"調劑檯","name":"腦思坦內服溶液用顆粒劑【粉劑】Piracetam GRANULES (1200mg/pkg)","loc":"ZAE右3","tag":"一般藥品區"},
{"code":"共用區2","cat":"調劑檯","name":"富帝芬貼片【水溶】Flurbiprofen PATCH (40mg/piece;4pcs)","loc":"大庫區最上層(箱裝)","tag":null},
{"code":"共用區3","cat":"調劑檯","name":"思舒酸痛凝膠 Etofenamate Gel (50mg/g;40g)","loc":"大庫區SXH右1","tag":null},
{"code":"共用區4","cat":"調劑檯","name":"愛憶欣口崩錠 Donepezil Orodispersible Tab. (10mg/tab)","loc":"直上","tag":null},
{"code":"GZA11","cat":"調劑檯","name":"牟靜錠 BroMAzepam (3mg/tab)","loc":"ZDB左2","tag":"四級管藥"},
{"code":"GZA1-2、3","cat":"調劑檯","name":"痛停 Aceclofenac (100mg/tab)","loc":"ZBA偏中","tag":"止痛區"},
{"code":"GZA14","cat":"調劑檯","name":"艾胃逆服咀嚼錠 Alginic Acid/Mag.carbonate/Alu.hydroxide (200/40/30mg/tab)","loc":"ZB腸胃左1","tag":null},
{"code":"GZA16","cat":"調劑檯","name":"欣律錠 Allopurinol (100mg/tab)","loc":"ZAA左2","tag":"一般藥品區"},
{"code":"GZA18","cat":"調劑檯","name":"樂咳痰舒長效錠 Ambroxol HCL TAB. (75mg/tab)","loc":"ZAA左1","tag":"一般藥品區"},
{"code":"GZA21","cat":"調劑檯","name":"德利能 Amitriptyline (25mg/tab)","loc":"ZB身心科左1","tag":null},
{"code":"GZA2-2、3","cat":"調劑檯","name":"安蒙西林膠囊 Amoxicillin cap. (250mg/cap)","loc":"ZBA左1","tag":"抗生素區"},
{"code":"GZA24","cat":"調劑檯","name":"樂可舒腸溶糖衣錠【錠】BisaCODYL TAB. (5mg/tab)","loc":"ZB腸胃科約左4","tag":null},
{"code":"GZA2-6、7","cat":"調劑檯","name":"立普妥膜衣錠 ATORvastatin Tab. (20mg/tab)","loc":"大庫02","tag":null},
{"code":"GZA28","cat":"調劑檯","name":"壓平樂 Atenolol Tab. (100mg/tab)","loc":"ZCB左1","tag":null},
{"code":"GZA31","cat":"調劑檯","name":"首利安錠 Amisulpride (200mg/tab)","loc":"ZB身心科左2","tag":null},
{"code":"GZA34","cat":"調劑檯","name":"諾快寧膜衣錠【錠】Amoxicillin/Clavulanate TAB. (1000mg/tab)","loc":"ZBA左2","tag":"抗生素區"},
{"code":"GZA3-6、7","cat":"調劑檯","name":"優力康 Benzbromarone (50mg/tab)","loc":"ZAA約左5","tag":"一般藥品區"},
{"code":"GZA38","cat":"調劑檯","name":"易得平錠 AZILsartan Tab. (40mg/tab)","loc":"ZCB左2","tag":null},
{"code":"GZA41","cat":"調劑檯","name":"胃可麗錠 BethaNECHOL Tab. (10mg/tab)","loc":"ZAA約左4","tag":"一般藥品區"},
{"code":"GZA44","cat":"調劑檯","name":"多巴定 Amantadine (100mg/tab)","loc":"ZAA左3","tag":"一般藥品區"},
{"code":"GZA46","cat":"調劑檯","name":"敏使朗 BetaHIStine Mesilate (12mg/tab)","loc":"ZCB約左4","tag":null},
{"code":"GZA48","cat":"調劑檯","name":"康肯 Bisoprolol (5mg/tab)","loc":"ZCB左3","tag":null},
{"code":"GZB11","cat":"調劑檯","name":"欣苷膜衣錠 Entecavir (0.5mg/tab)","loc":"ZAB左1","tag":"一般藥品區"},
{"code":"GZB1-2、3","cat":"調劑檯","name":"待匹力達糖衣錠 Dipyridamole TAB. (25mg/tab)","loc":"ZCA左3","tag":null},
{"code":"GZB14","cat":"調劑檯","name":"達理痛 Febuxostat Tab. (80mg/tab)","loc":"ZAB左3","tag":"一般藥品區"},
{"code":"GZB16","cat":"調劑檯","name":"弗尼利脂寧 Fenofibrate (160mg/tab)","loc":"ZDA左2","tag":null},
{"code":"GZB18","cat":"調劑檯","name":"維諾心 Dipyridamole TAB. (75mg/tab)","loc":"ZCC左2","tag":null},
{"code":"GZB21","cat":"調劑檯","name":"適尿通軟膠囊 Dutasteride (0.5mg/cap)","loc":"ZAA右1","tag":"一般藥品區"},
{"code":"GZB22","cat":"調劑檯","name":"萬克適錠 Etoricoxib (60mg/tab)","loc":"ZBA右3","tag":"止痛區"},
{"code":"GZB24","cat":"調劑檯","name":"維他葡萄糖鐵 Ferrous Gluconate/Thiamine/Ascorbic Acid TAB. (300/10/30mg/tab)","loc":"ZAB左5","tag":"一般藥品區"},
{"code":"GZB26","cat":"調劑檯","name":"杏銀 Ginkgo Biloba extract Tab. (40mg/tab)","loc":"ZAB左5","tag":"一般藥品區"},
{"code":"GZB28","cat":"調劑檯","name":"舒腦 Flunarizine (5mg/cap)","loc":"ZCA左4","tag":null},
{"code":"GZB31","cat":"調劑檯","name":"離憂 Escitalopram (10mg/tab)","loc":"ZB身心科約左5","tag":null},
{"code":"GZB32","cat":"調劑檯","name":"解鬱膠囊 FLUOxetine HCl (20mg/cap)","loc":"ZB身心科偏中","tag":null},
{"code":"GZB34","cat":"調劑檯","name":"胃樂順膜衣錠 Famotidine TAB. (20mg/tab)","loc":"ZB腸胃科中","tag":null},
{"code":"GZB37","cat":"調劑檯","name":"福安源錠 FluDIAzepam (0.25mg/tab)","loc":"ZDC左2","tag":null},
{"code":"GZB38","cat":"調劑檯","name":"優泰脂膜衣錠【複】Ezetimibe/Atorvastatin Tab. (10mg/20mg/tab)","loc":"ZCC中","tag":null},
{"code":"GZB41","cat":"調劑檯","name":"瘡寧膜衣錠 Hydroxychloroquine (200mg/tab)","loc":"ZAB右3","tag":"一般藥品區"},
{"code":"GZB42","cat":"調劑檯","name":"和寧錠【小劑量】Haloperidol TAB. (0.5mg/tab)","loc":"ZB身心科約左2、3","tag":null},
{"code":"GZB43","cat":"調劑檯","name":"克胺寧錠 HydroxyZINE (25mg/tab)","loc":"ZAB右4","tag":"一般藥品區"},
{"code":"GZB44","cat":"調劑檯","name":"鐵達寧咀嚼錠 Ferric Hydroxide Polymaltose Complex (100mg/tab)","loc":"ZAB約左3","tag":"一般藥品區"},
{"code":"GZB45","cat":"調劑檯","name":"血得平錠 Hydralazine Tab. (25mg/tab)","loc":"ZCC偏中","tag":null},
{"code":"GZB46","cat":"調劑檯","name":"悠樂丁 EstaZOLAM (2mg/tab)","loc":"ZDC左1","tag":null},
{"code":"GZB47","cat":"調劑檯","name":"葉酸 Folic acid (5mg/tab)","loc":"ZAB左2","tag":"一般藥品區"},
{"code":"GZB48","cat":"調劑檯","name":"舒利諾【錠】Furosemide TAB. (40mg/tab)","loc":"ZCC偏中","tag":null},
{"code":"GZC11","cat":"調劑檯","name":"耐比洛錠 Nebivolol Tab. (5mg/tab)","loc":"ZCD約左3","tag":null}
];
